### PR TITLE
feat: composite ordering

### PR DESCRIPTION
**Pull request by nicoecheza**
closes https://github.com/decentraland/sdk/issues/871

### Summary
🌲🛠️🚚

This pull request adds drag and drop functionality to the `Hierarchy` and `ProjectView` components, and introduces a new `Nodes` component to store and manipulate the entity hierarchy in the scene. It also updates the `useTree` hook, the `@dcl/inspector` operations, and some migration functions to use the `Nodes` component. It fixes some bugs and code style issues, and adds some tests and utils for the new features.

> _We're haulin' on the `Nodes` component, boys and girls_
> _We're draggin' and droppin' the entities in the world_
> _We're fixin' up the `Tree` and the `Hierarchy`_
> _We're workin' on the editor, one, two, three_

### Walkthrough
*  Add `Nodes` component to store the hierarchy of the entities in the scene ([link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-4111260f5540363a0149bba9925eee36109bc213af87c97447294d6d39e8d227R3), [link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-4111260f5540363a0149bba9925eee36109bc213af87c97447294d6d39e8d227L14-R20), [link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-4111260f5540363a0149bba9925eee36109bc213af87c97447294d6d39e8d227R26), [link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-4111260f5540363a0149bba9925eee36109bc213af87c97447294d6d39e8d227R32), [link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-4111260f5540363a0149bba9925eee36109bc213af87c97447294d6d39e8d227L75-R89))
*  Add `Node` type to represent a node in the hierarchy, with an `entity` and a `children` property ([link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-4111260f5540363a0149bba9925eee36109bc213af87c97447294d6d39e8d227R3), [link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-4111260f5540363a0149bba9925eee36109bc213af87c97447294d6d39e8d227L14-R20))
*  Add `DropType` type and `calculateDropType` function to handle different types of drop events for the drag and drop feature of the `Tree` component ([link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-d37571a5b872b387aab3bbd84051748ed3b2a8f5b972237d18b56d150ed57fd1R11), [link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-2a6fdff56ea081a04e5373180bcd3eb62e0a1086acc473bbe561a29a0e766ddaR1-R9))
*  Add `DisclosureWidget` component to render the arrow icon that indicates if a node can be expanded or collapsed ([link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-d37571a5b872b387aab3bbd84051748ed3b2a8f5b972237d18b56d150ed57fd1R253))
*  Add `canDrag` and `canReorder` props to the `Tree` component, to determine if a node can be dragged and reordered ([link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-d37571a5b872b387aab3bbd84051748ed3b2a8f5b972237d18b56d150ed57fd1L28-R34), [link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-d37571a5b872b387aab3bbd84051748ed3b2a8f5b972237d18b56d150ed57fd1L62-R73), [link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-d37571a5b872b387aab3bbd84051748ed3b2a8f5b972237d18b56d150ed57fd1L86-R100), [link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-d37571a5b872b387aab3bbd84051748ed3b2a8f5b972237d18b56d150ed57fd1L97-R145), [link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-a6dc7df53ae7287bbf316eb2eca4794790b0110845c6c9388c8a101fb9a7d2b0R39-R40), [link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-a6dc7df53ae7287bbf316eb2eca4794790b0110845c6c9388c8a101fb9a7d2b0R74-R75))
*  Add `canDrag` and `canReorder` functions to the `useTree` hook, to provide some validation logic for the drag and drop feature ([link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-2b17dc2147f287bb3a8e26487ddd0a5a7e28f7d5070206f83b049ba03447fd77R204-R205))
*  Add `reorder` function to the `operations` object, to reorder the nodes in the `Nodes` component value based on the source, target, and new parent entities ([link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-dc3c30163a189bdd1f1d234e5ac730e7d99621a26dfc2fac77cf1a3b17b164b4R8), [link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-dc3c30163a189bdd1f1d234e5ac730e7d99621a26dfc2fac77cf1a3b17b164b4R28))
*  Add `runMigrations` function to perform some migrations on the engine context, such as removing the old `EntityNode` components and building the `Nodes` component value if it does not exist ([link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-764ec34e090b79d70cfe652ca421c47c12d0a262577f8f2b05c98ccfef9e3576R28-R35), [link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-764ec34e090b79d70cfe652ca421c47c12d0a262577f8f2b05c98ccfef9e3576R52-R53))
*  Add `buildNodesHierarchy` and `buildNodesHierarchyIfNotExists` functions to build the `Nodes` component value from the current engine status ([link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-877845caaf5500973fa70ba6bc387c96e67defcad113ff25e1f9a5b173a4fd86R1-R57))
*  Add `pushChild` and `removeNode` functions to add or remove a node from the tree, and return the updated tree ([link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-9d4ad6547334c87ce357aef8bc831e1efae1e5ec63f4ab19870e28b895c43722R1-R58), [link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-7f75d49492295116181da1753a4fa846901d9296136ff1da05ed6eff86a75a78L2-R18))
*  Add tests for the `buildNodesHierarchy` and `buildNodesHierarchyIfNotExists` functions, using different composites and engine contexts ([link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-e1eaa6ca5c79af78968656e392ce0405f27b52ea6984a1b55d7cd449cebba00aR1-R40))
*  Rename `onSetParent` prop to `onDrop` in the `Hierarchy` and `ProjectView` components, to reflect the new logic of handling different types of drop events ([link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-a6dc7df53ae7287bbf316eb2eca4794790b0110845c6c9388c8a101fb9a7d2b0L55-R57), [link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-61e1c2ce0303a20e260561e4edec1c89d3fb292e7c99952ed958e1056564a491L207-R207))
*  Modify the `useDrop` hook logic in the `Tree` component, to use the `calculateDropType` function and the `canReorder` function, and to pass the drop type value to the `onDrop` prop function ([link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-d37571a5b872b387aab3bbd84051748ed3b2a8f5b972237d18b56d150ed57fd1L97-R145))
*  Modify the `setParent` function in the `useTree` hook, to use the `getNewParent` function and the `reorder` function, and to handle different types of drop events ([link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-2b17dc2147f287bb3a8e26487ddd0a5a7e28f7d5070206f83b049ba03447fd77L82-R108))
*  Modify the `useTree` hook logic, to use the `Nodes` component instead of the `Transform` component, and to return an array of nodes ([link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-2b17dc2147f287bb3a8e26487ddd0a5a7e28f7d5070206f83b049ba03447fd77L20-R23), [link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-2b17dc2147f287bb3a8e26487ddd0a5a7e28f7d5070206f83b049ba03447fd77L36-L37), [link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-2b17dc2147f287bb3a8e26487ddd0a5a7e28f7d5070206f83b049ba03447fd77L45-R43))
*  Modify the `addChild` function, to return the child entity and to update the `Nodes` component value with the `pushChild` function ([link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-77b16a31e57e19c8a89c27566af0216e21fa6d477da31f44f95decec739baf47L1-R14))
*  Modify the `removeEntity` function, to update the `Nodes` component value with the `removeNode` function for every entity iterator in the component entity tree ([link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-9cb094d1bc6f50198097b30f94b5916995867dc66ffabd6104323edebf6685cdL2-R13))
*  Modify the `generateMinimalComposite` and `generateMainComposite` functions, to add the `Nodes` component to the engine and set its value to the minimal or main hierarchy ([link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-1833e802286e88c2b90e9952933a0710b3e5bb0a92dfe88137c87ee7ae3aea04R35-R42), [link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-1833e802286e88c2b90e9952933a0710b3e5bb0a92dfe88137c87ee7ae3aea04R108-R116))
*  Modify the `createTempEngineContext` and `generateMinimalComposite` functions, to export them as named exports ([link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-1833e802286e88c2b90e9952933a0710b3e5bb0a92dfe88137c87ee7ae3aea04L10-R10), [link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-1833e802286e88c2b90e9952933a0710b3e5bb0a92dfe88137c87ee7ae3aea04L24-R24))
*  Modify the `generateMainComposite` function, to add the `gltfEntity` to the engine before creating its components, and to remove the duplicate line that adds it again ([link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-1833e802286e88c2b90e9952933a0710b3e5bb0a92dfe88137c87ee7ae3aea04L59-R70), [link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-1833e802286e88c2b90e9952933a0710b3e5bb0a92dfe88137c87ee7ae3aea04L88))
*  Modify the `Tree` component and its CSS styles, to add some border styles for different drop types and to adjust the margin and padding for the tree and the item area ([link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-5d68afaad2fc1ce915bad17cc9f58a8fc3b7b39a4d1c2eebb592d8bbbacdad73L7-R35), [link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-5d68afaad2fc1ce915bad17cc9f58a8fc3b7b39a4d1c2eebb592d8bbbacdad73L30-R44), [link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-5d68afaad2fc1ce915bad17cc9f58a8fc3b7b39a4d1c2eebb592d8bbbacdad73L46-R64), [link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-d37571a5b872b387aab3bbd84051748ed3b2a8f5b972237d18b56d150ed57fd1L165-R214))
*  Modify the `Tree` component, to use a ref for the item area element and to pass the `drag` and `drop` functions to it ([link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-d37571a5b872b387aab3bbd84051748ed3b2a8f5b972237d18b56d150ed57fd1L1-R2), [link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-d37571a5b872b387aab3bbd84051748ed3b2a8f5b972237d18b56d150ed57fd1R83), [link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-d37571a5b872b387aab3bbd84051748ed3b2a8f5b972237d18b56d150ed57fd1L150-R188))
*  Modify the `Tree` component, to use a custom component for the disclosure widget and to simplify the rendering of the children nodes ([link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-d37571a5b872b387aab3bbd84051748ed3b2a8f5b972237d18b56d150ed57fd1R232-R246), [link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-d37571a5b872b387aab3bbd84051748ed3b2a8f5b972237d18b56d150ed57fd1L210-R260))
*  Modify the `initRpcMethods` function, to remove the call to the `removeLegacyEntityNodeComponents` function ([link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-58866fcae4b48b46e34b329aa3bc70e3f27ce79098c5f291146d945f51a60e5cL24-L26))
*  Modify the `removeLegacyEntityNodeComponents` function, to move it to the `migrations` folder ([link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-7d7e0ca578d35b0e4ba60e5fa403744131f403a62965d08372703f2f2dbde343))
*  Remove the trailing comma from the `jest-puppeteer.config.js` file ([link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-1bfd68a1a71fd4f124415ef7418066a68d23b777b21fd879b6757af36515c18fL7-R7))
*  Remove the import statement for the `removeLegacyEntityNodeComponents` function from the `rpc-methods.ts` file ([link](https://github.com/decentraland/js-sdk-toolchain/pull/679/files?diff=unified&w=0#diff-58866fcae4b48b46e34b329aa3bc70e3f27ce79098c5f291146d945f51a60e5cL10))

### CODE REVIEW

**Comment by cazala** [comment]
I think there's a styling issue, when I drag a child over a parent it shows the indicator that it will be placed after the parent, but it moves it inside (where it already was, so it does nothing, but the indicator suggests that it would be moved outside, below the parent).

https://github.com/decentraland/js-sdk-toolchain/assets/2781777/6f246502-e67e-4909-8f57-630808312447

**Comment by nicoecheza** [comment]
> I think there's a styling issue, when I drag a child over a parent it shows the indicator that it will be placed after the parent, but it moves it inside (where it already was, so it does nothing, but the indicator suggests that it would be moved outside, below the parent).
> 
>  reorder.mp4

yeah, it's the correct behaviour but the wrong UI. Will take a look at it 👍

**Comment by cazala** [comment]
I think when a node has children it's not possible to drag an entity after it? Look at this example, test1 has children (test2), and I can't drag test4 between test1 and test3:


https://github.com/decentraland/js-sdk-toolchain/assets/2781777/e06b7a23-2b9c-4ccd-b302-8254878628ce

Also there seems to be 2 hover states? One that puts the dropped entity inside at the top and the other puts the entity inside at the bottom of the list.

I think it would also be nice to highlight somehow when an entity is going to be dropped inside another, because currently we have the "after" hightlight but the "inside" doesnt actually highlight anything

**Comment by nicoecheza** [comment]
fixed the issue for dropping after parents + added a background color for dropping inside a parent that makes it more clear 👌 

Screen Shot 2023-07-14 at 10 15 44

**Review by cazala — APPROVED** [review]

**Pull request merged**
