### PR TITLE
feat: Add Inspector EntityDropdown Field

### PR DESCRIPTION
**Pull request by cyaiox**
This PR adds a util EntityDropdown field to show entities based on components.

image

Closes https://github.com/decentraland/sdk/issues/978

### CODE REVIEW

**Comment by cazala** [comment]
I noticed that the padding between the fields is gone in this PR, I don't know if it's coming from the changes in this branch, but I don't see it like that on other PRs

Screenshot 2023-10-31 at 10 21 57

**Comment by cyaiox** [comment]
> I noticed that the padding between the fields is gone in this PR, I don't know if it's coming from the changes in this branch, but I don't see it like that on other PRs

You're right, I removed the TextboxField margin in this PR: https://github.com/decentraland/js-sdk-toolchain/pull/806/files#diff-c8c97e2ba0e6703f0fc5316c5927e8c163ca9db1f3f394cf43a53656d387fc32L7 

Fixing it

**Comment by cazala** [comment]
there's another issue i noticed with the dropdowns: 

https://github.com/decentraland/js-sdk-toolchain/assets/2781777/a938b714-9322-4bad-955a-290d6cecb811

**Review by cazala — APPROVED** [review]
Looking great :D

**Pull request merged**
